spring:
  profiles:
    active: local

  # Spring Batch가 실행될 때 Program arguments로 job.name값이 넘어오면 해당 값과 일치하는 Job만 실행
  batch:
    job:
      names: ${job.name:NONE} # job.name이 있으면 job.name을 할당하고 없으면 NONE 할당
      # 이 때 Spring Batch에 NONE이 할당되면 어떤 배치도 실행하지 않겠다는 의미!
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver
